/**
 * Minimal ground-truth test:
 * "No GitHub OAuth required via synthesized legacy-token env"
 * (add-agent-oneclick-prebuilt-deploy, task 1.6 / GATE 5 of scripts/quick-deploy.sh)
 *
 * Exercises the GATE 5 bash logic IN ISOLATION (no docker, no network, no pull)
 * by running just the synthesis fragment against a temp dir.
 *
 * Assertions mirror the requirement verbatim:
 *   - AUTH_TOKEN_LEGACY_ENABLED=true  (the seam that makes prebuilt images boot with NO OAuth)
 *   - AUTH_TOKEN is set (random, non-empty, prefixed cap_)
 *   - SESSION_SECRET and CODEX_CRED_ENC_KEY are set (random 32-byte hex)
 *   - WEB_ORIGIN is a localhost URL
 *   - CAP_VERSION is pinned to whatever the caller passes
 *   - Synthesis is IDEMPOTENT: a second run reuses the existing .env (non-destructive)
 *
 * Run: node legacy-token-synthesized-env.test.mjs
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

let passed = 0;
let failed = 0;

function assert(cond, label) {
  if (cond) { console.log(`  PASS  ${label}`); passed++; }
  else       { console.error(`  FAIL  ${label}`); failed++; }
}

/** Parse KEY=VALUE lines into a map (ignores comments / blank lines). */
function parseEnv(text) {
  const map = {};
  for (const line of text.split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) map[m[1]] = m[2];
  }
  return map;
}

/**
 * Run only GATE 5 of quick-deploy.sh in an isolated temp dir by extracting the
 * synthesis fragment and executing it with bash.  We pass WORKDIR + CAP_VERSION
 * as environment variables and stub out the gates that come before/after it.
 */
function runGate5(workdir, capVersion = 'v0.21.0') {
  // This is the exact verbatim GATE 5 block from scripts/quick-deploy.sh,
  // extracted without modification so the test is a literal re-execution.
  const gate5 = `
set -euo pipefail
CAP_VERSION="\${CAP_VERSION:-latest}"
WORKDIR="\${CAP_WORKDIR:-\$PWD}"
API_PORT="\${API_PORT:-8080}"
WEB_PORT="\${WEB_PORT:-3000}"

warn(){ printf 'warn: %s\n' "\$*" >&2; }
die(){  printf 'error: %s\n' "\$*" >&2; exit 1; }

ENV_FILE="\$WORKDIR/.env"
if [ -f "\$ENV_FILE" ]; then
  echo "  \$ENV_FILE exists — reusing as-is (not overwriting)."
  TOKEN="\$(awk -F= '/^AUTH_TOKEN=/{print \$2; exit}' "\$ENV_FILE")"
else
  TOKEN="cap_\$(openssl rand -hex 24)"
  ( umask 077; cat > "\$ENV_FILE" <<EOF
# Generated by scripts/quick-deploy.sh — LOCAL TRIAL via PREBUILT images, legacy-token auth.
# This is NOT an OAuth-first production deploy. Keep this file out of version control.
CAP_VERSION=\${CAP_VERSION}
AUTH_TOKEN_LEGACY_ENABLED=true
AUTH_TOKEN=\${TOKEN}
SESSION_SECRET=\$(openssl rand -hex 32)
CODEX_CRED_ENC_KEY=\$(openssl rand -hex 32)
# Same-host trial: web (:\${WEB_PORT}) and api (:\${API_PORT}) on localhost.
WEB_ORIGIN=http://localhost:\${WEB_PORT}
EOF
  )
  echo "  wrote \$ENV_FILE with a random legacy token (gitignored)"
fi
[ -n "\${TOKEN:-}" ] || die "could not resolve AUTH_TOKEN from \$ENV_FILE"
`;
  execFileSync('bash', ['-c', gate5], {
    env: { ...process.env, CAP_WORKDIR: workdir, CAP_VERSION: capVersion },
    stdio: 'pipe',
  });
}

// ── case 1: fresh synthesis — all required keys are present with correct values ─
console.log('\n=== case 1: fresh .env synthesis (no pre-existing file) ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  runGate5(dir, 'v0.21.0');

  assert(existsSync(envPath), 'case1: .env file was created');

  const env = parseEnv(readFileSync(envPath, 'utf8'));

  // The key requirement: NO OAuth — legacy-token path explicitly enabled.
  assert(env.AUTH_TOKEN_LEGACY_ENABLED === 'true',
    'case1: AUTH_TOKEN_LEGACY_ENABLED=true (prebuilt images boot without GitHub OAuth)');

  // Bearer token is present and uses the cap_ prefix (safe prefix, not cap_sk_/mcp_).
  assert(typeof env.AUTH_TOKEN === 'string' && env.AUTH_TOKEN.startsWith('cap_'),
    'case1: AUTH_TOKEN is set and starts with cap_');
  assert(env.AUTH_TOKEN.length > 4,
    'case1: AUTH_TOKEN has non-trivial length beyond the prefix');

  // Two additional secrets must be present and non-empty hex.
  assert(/^[0-9a-f]{64}$/.test(env.SESSION_SECRET),
    'case1: SESSION_SECRET is a 32-byte hex string');
  assert(/^[0-9a-f]{64}$/.test(env.CODEX_CRED_ENC_KEY),
    'case1: CODEX_CRED_ENC_KEY is a 32-byte hex string');

  // WEB_ORIGIN must point at localhost (no external OAuth redirect possible).
  assert(typeof env.WEB_ORIGIN === 'string' && env.WEB_ORIGIN.startsWith('http://localhost'),
    'case1: WEB_ORIGIN is a localhost URL (no external OAuth redirect)');

  // CAP_VERSION is pinned in the generated file.
  assert(env.CAP_VERSION === 'v0.21.0',
    'case1: CAP_VERSION is pinned in the generated .env');

  // All three generated secrets must be distinct (no copy-paste collision).
  const hexSecrets = [env.SESSION_SECRET, env.CODEX_CRED_ENC_KEY];
  const tokenHex = env.AUTH_TOKEN.replace(/^cap_/, '');
  assert(new Set([...hexSecrets, tokenHex]).size === 3,
    'case1: AUTH_TOKEN, SESSION_SECRET, CODEX_CRED_ENC_KEY are all distinct');
}

// ── case 2: idempotent reuse — an existing .env is NEVER overwritten ────────────
console.log('\n=== case 2: existing .env is reused without overwriting ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  // Write a sentinel .env that must survive the second run unchanged.
  const sentinel = 'AUTH_TOKEN=DO-NOT-OVERWRITE\nAUTH_TOKEN_LEGACY_ENABLED=true\n';
  writeFileSync(envPath, sentinel, { mode: 0o600 });

  // Running GATE 5 a second time must exit 0 and leave the file unchanged.
  let threw = false;
  try { runGate5(dir, 'v0.21.0'); }
  catch (e) { threw = true; console.error('  runGate5 threw:', e.message); }

  assert(!threw, 'case2: GATE 5 exits 0 even when .env already exists');
  assert(readFileSync(envPath, 'utf8') === sentinel,
    'case2: existing .env is left UNCHANGED (idempotent, non-destructive)');
}

// ── case 3: no GITHUB_* / OAUTH keys injected by the synthesis ─────────────────
console.log('\n=== case 3: synthesized .env contains no GitHub OAuth keys ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  runGate5(dir, 'v0.21.0');

  const raw = readFileSync(envPath, 'utf8');
  // OAuth-specific keys that would indicate the OAuth path is wired in.
  const oauthKeys = ['GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET', 'GITHUB_OAUTH', 'OAUTH_'];
  for (const key of oauthKeys) {
    assert(!raw.includes(key),
      `case3: synthesized .env does not contain OAuth key ${key}`);
  }
}

// ── summary ──────────────────────────────────────────────────────────────────
console.log(`\n${'─'.repeat(56)}`);
console.log(`Results: ${passed} passed, ${failed} failed`);
if (failed === 0) { console.log('ALL TESTS PASSED'); process.exit(0); }
else { console.error('SOME TESTS FAILED'); process.exit(1); }
