/**
 * Minimal ground-truth test:
 * "No GitHub OAuth required via synthesized legacy-token env"
 * (add-agent-oneclick-prebuilt-deploy, task 1.6 / GATE 5 of scripts/quick-deploy.sh)
 *
 * Exercises the GATE 5 bash logic IN ISOLATION (no docker, no network, no pull)
 * by running the synthesis/update fragment against a temp dir.
 *
 * Assertions mirror the requirement verbatim:
 *   - AUTH_TOKEN_LEGACY_ENABLED=true  (the seam that makes prebuilt images boot with NO OAuth)
 *   - AUTH_TOKEN is set (random, non-empty, prefixed cap_)
 *   - SESSION_SECRET and CODEX_CRED_ENC_KEY are set (random 32-byte hex)
 *   - WEB_ORIGIN is a localhost URL
 *   - CAP_VERSION is pinned to whatever the caller passes
 *   - CAP_SANDBOX_PROVIDER is written for the selected provider
 *   - BoxLite provider values are appended when the selected provider is boxlite
 *   - Existing secret values are preserved; missing operational defaults may be appended
 *
 * Run: node legacy-token-synthesized-env.test.mjs
 */

import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

let passed = 0;
let failed = 0;

function assert(cond, label) {
  if (cond) { console.log(`  PASS  ${label}`); passed++; }
  else       { console.error(`  FAIL  ${label}`); failed++; }
}

/** Parse KEY=VALUE lines into a map (ignores comments / blank lines). */
function parseEnv(text) {
  const map = {};
  for (const line of text.split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) map[m[1]] = m[2];
  }
  return map;
}

/**
 * Run only GATE 5 of quick-deploy.sh in an isolated temp dir. We pass WORKDIR,
 * CAP_VERSION, and provider env variables, then stub out the gates before/after it.
 */
function runGate5(workdir, capVersion = 'v0.21.0', provider = 'aio', extraEnv = {}) {
  const gate5 = `
set -euo pipefail
CAP_VERSION="\${CAP_VERSION:-latest}"
WORKDIR="\${CAP_WORKDIR:-\$PWD}"
API_PORT="\${API_PORT:-8080}"
WEB_PORT="\${WEB_PORT:-3000}"
SELECTED_PROVIDER="\${CAP_SANDBOX_PROVIDER:-aio}"
CAP_IMAGE_PLATFORM="\${CAP_IMAGE_PLATFORM:-}"

warn(){ printf 'warn: %s\n' "\$*" >&2; }
die(){  printf 'error: %s\n' "\$*" >&2; exit 1; }

ENV_FILE="\$WORKDIR/.env"
env_file_value(){
  local key="\$1"
  [ -f "\$ENV_FILE" ] || return 0
  awk -F= -v k="\$key" '\$1 == k { print substr(\$0, length(k) + 2); exit }' "\$ENV_FILE" 2>/dev/null || true
}
value_for(){
  local key="\$1"
  local from_process="\${!key:-}"
  if [ -n "\$from_process" ]; then
    printf '%s\\n' "\$from_process"
  else
    env_file_value "\$key"
  fi
}
has_env_key(){
  local key="\$1"
  [ -f "\$ENV_FILE" ] && awk -F= -v k="\$key" '\$1 == k { found = 1 } END { exit found ? 0 : 1 }' "\$ENV_FILE" 2>/dev/null
}
set_env_if_missing(){
  local key="\$1" value="\$2"
  [ -n "\$value" ] || return 0
  if ! has_env_key "\$key"; then
    printf '%s=%s\\n' "\$key" "\$value" >>"\$ENV_FILE"
  fi
}
set_env_value(){
  local key="\$1" value="\$2" tmp
  [ -n "\$value" ] || return 0
  if [ ! -f "\$ENV_FILE" ]; then
    printf '%s=%s\\n' "\$key" "\$value" >"\$ENV_FILE"
    return
  fi
  tmp="\${ENV_FILE}.captmp"
  awk -F= -v k="\$key" -v v="\$value" '
    \$1 == k && !done { print k "=" v; done = 1; next }
    { print }
    END { if (!done) print k "=" v }
  ' "\$ENV_FILE" >"\$tmp"
  chmod 600 "\$tmp" 2>/dev/null || true
  mv "\$tmp" "\$ENV_FILE"
}
require_value(){
  local key="\$1" value
  value="\$(value_for "\$key")"
  [ -n "\$value" ] || die "\$key is required for CAP_SANDBOX_PROVIDER=\$SELECTED_PROVIDER"
  printf '%s\\n' "\$value"
}
if [ -f "\$ENV_FILE" ]; then
  echo "  \$ENV_FILE exists — preserving existing values."
  TOKEN="\$(awk -F= '/^AUTH_TOKEN=/{print \$2; exit}' "\$ENV_FILE")"
else
  TOKEN="cap_\$(openssl rand -hex 24)"
  ( umask 077; cat > "\$ENV_FILE" <<EOF
# Generated by scripts/quick-deploy.sh — LOCAL TRIAL via PREBUILT images, legacy-token auth.
# This is NOT a local-account production deploy. Keep this file out of version control.
CAP_VERSION=\${CAP_VERSION}
CAP_SANDBOX_PROVIDER=\${SELECTED_PROVIDER}
AUTH_TOKEN_LEGACY_ENABLED=true
AUTH_TOKEN=\${TOKEN}
SESSION_SECRET=\$(openssl rand -hex 32)
CODEX_CRED_ENC_KEY=\$(openssl rand -hex 32)
# Same-host trial: web (:\${WEB_PORT}) and api (:\${API_PORT}) on localhost.
WEB_ORIGIN=http://localhost:\${WEB_PORT}
EOF
  )
  echo "  wrote \$ENV_FILE with a random legacy token (gitignored)"
fi
[ -n "\${TOKEN:-}" ] || die "could not resolve AUTH_TOKEN from \$ENV_FILE"
set_env_value CAP_VERSION "\$CAP_VERSION"
set_env_value CAP_SANDBOX_PROVIDER "\$SELECTED_PROVIDER"
[ -n "\$CAP_IMAGE_PLATFORM" ] && set_env_value CAP_IMAGE_PLATFORM "\$CAP_IMAGE_PLATFORM"
if [ "\$SELECTED_PROVIDER" = "boxlite" ]; then
  boxlite_endpoint="\$(require_value BOXLITE_ENDPOINT)"
  boxlite_token="\$(require_value BOXLITE_API_TOKEN)"
  boxlite_image="\$(value_for BOXLITE_IMAGE)"
  boxlite_image_map="\$(value_for BOXLITE_IMAGE_MAP)"
  [ -n "\$boxlite_image" ] || [ -n "\$boxlite_image_map" ] || die "BOXLITE_IMAGE or BOXLITE_IMAGE_MAP is required for CAP_SANDBOX_PROVIDER=boxlite"
  set_env_if_missing BOXLITE_ENDPOINT "\$boxlite_endpoint"
  set_env_if_missing BOXLITE_API_TOKEN "\$boxlite_token"
  set_env_if_missing BOXLITE_IMAGE "\$boxlite_image"
  set_env_if_missing BOXLITE_IMAGE_MAP "\$boxlite_image_map"
  set_env_if_missing BOXLITE_PROVIDER_ID boxlite
  set_env_if_missing BOXLITE_PROVIDER_PRIORITY 100
  set_env_if_missing BOXLITE_PROVIDER_LOCATION local
  set_env_if_missing BOXLITE_WORKSPACE_PATH /workspace
  set_env_if_missing BOXLITE_SANDBOX_ID_PREFIX cap-boxlite-
  set_env_if_missing BOXLITE_SANDBOX_MODE workspace-write
  set_env_if_missing BOXLITE_CLIENT_MODE rest
  set_env_if_missing BOXLITE_TIMEOUT_MS 30000
  set_env_if_missing BOXLITE_TERMINAL_MODE pty
  set_env_if_missing BOXLITE_CAPABILITIES terminal.websocket,terminal.interactive,command.exec,workspace.git.materialize,workspace.git.deliver,workspace.archive.transfer,lifecycle.readopt,lifecycle.readoption
fi
`;
  execFileSync('bash', ['-c', gate5], {
    env: {
      ...process.env,
      ...extraEnv,
      CAP_WORKDIR: workdir,
      CAP_VERSION: capVersion,
      CAP_SANDBOX_PROVIDER: provider,
    },
    stdio: 'pipe',
  });
}

// ── case 1: fresh synthesis — all required keys are present with correct values ─
console.log('\n=== case 1: fresh .env synthesis (no pre-existing file) ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  runGate5(dir, 'v0.21.0');

  assert(existsSync(envPath), 'case1: .env file was created');

  const env = parseEnv(readFileSync(envPath, 'utf8'));

  // The key requirement: NO OAuth — legacy-token path explicitly enabled.
  assert(env.AUTH_TOKEN_LEGACY_ENABLED === 'true',
    'case1: AUTH_TOKEN_LEGACY_ENABLED=true (prebuilt images boot without GitHub OAuth)');

  // Bearer token is present and uses the cap_ prefix (safe prefix, not cap_sk_/mcp_).
  assert(typeof env.AUTH_TOKEN === 'string' && env.AUTH_TOKEN.startsWith('cap_'),
    'case1: AUTH_TOKEN is set and starts with cap_');
  assert(env.AUTH_TOKEN.length > 4,
    'case1: AUTH_TOKEN has non-trivial length beyond the prefix');

  // Two additional secrets must be present and non-empty hex.
  assert(/^[0-9a-f]{64}$/.test(env.SESSION_SECRET),
    'case1: SESSION_SECRET is a 32-byte hex string');
  assert(/^[0-9a-f]{64}$/.test(env.CODEX_CRED_ENC_KEY),
    'case1: CODEX_CRED_ENC_KEY is a 32-byte hex string');

  // WEB_ORIGIN must point at localhost (no external OAuth redirect possible).
  assert(typeof env.WEB_ORIGIN === 'string' && env.WEB_ORIGIN.startsWith('http://localhost'),
    'case1: WEB_ORIGIN is a localhost URL (no external OAuth redirect)');

  // CAP_VERSION is pinned in the generated file.
  assert(env.CAP_VERSION === 'v0.21.0',
    'case1: CAP_VERSION is pinned in the generated .env');
  assert(env.CAP_SANDBOX_PROVIDER === 'aio',
    'case1: CAP_SANDBOX_PROVIDER is written for the selected provider');

  // All three generated secrets must be distinct (no copy-paste collision).
  const hexSecrets = [env.SESSION_SECRET, env.CODEX_CRED_ENC_KEY];
  const tokenHex = env.AUTH_TOKEN.replace(/^cap_/, '');
  assert(new Set([...hexSecrets, tokenHex]).size === 3,
    'case1: AUTH_TOKEN, SESSION_SECRET, CODEX_CRED_ENC_KEY are all distinct');
}

// ── case 2: idempotent reuse — secrets preserved, version/provider corrected ───
console.log('\n=== case 2: existing .env preserves secrets and updates version/provider ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  // Write a sentinel .env with secrets that must survive and stale operational
  // values that must be corrected so /version cannot remain unknown/latest.
  const sentinel = [
    'AUTH_TOKEN=DO-NOT-OVERWRITE',
    'AUTH_TOKEN_LEGACY_ENABLED=true',
    'CAP_VERSION=unknown',
    'CAP_SANDBOX_PROVIDER=control-plane',
    '',
  ].join('\n');
  writeFileSync(envPath, sentinel, { mode: 0o600 });

  // Running GATE 5 a second time must exit 0 and preserve existing secrets while
  // updating non-secret operational defaults.
  let threw = false;
  try { runGate5(dir, 'v0.21.0'); }
  catch (e) { threw = true; console.error('  runGate5 threw:', e.message); }

  assert(!threw, 'case2: GATE 5 exits 0 even when .env already exists');
  const updated = readFileSync(envPath, 'utf8');
  const env = parseEnv(updated);
  assert(env.AUTH_TOKEN === 'DO-NOT-OVERWRITE',
    'case2: existing AUTH_TOKEN is preserved');
  assert(env.AUTH_TOKEN_LEGACY_ENABLED === 'true',
    'case2: existing legacy-token flag is preserved');
  assert(env.CAP_VERSION === 'v0.21.0',
    'case2: stale CAP_VERSION is replaced with the resolved release tag');
  assert(env.CAP_SANDBOX_PROVIDER === 'aio',
    'case2: stale CAP_SANDBOX_PROVIDER is replaced');
}

// ── case 3: no GITHUB_* / OAUTH keys injected by the synthesis ─────────────────
console.log('\n=== case 3: synthesized .env contains no GitHub OAuth keys ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  runGate5(dir, 'v0.21.0');

  const raw = readFileSync(envPath, 'utf8');
  // OAuth-specific keys that would indicate the OAuth path is wired in.
  const oauthKeys = ['GITHUB_CLIENT_ID', 'GITHUB_CLIENT_SECRET', 'GITHUB_OAUTH', 'OAUTH_'];
  for (const key of oauthKeys) {
    assert(!raw.includes(key),
      `case3: synthesized .env does not contain OAuth key ${key}`);
  }
}

// ── case 4: BoxLite provider defaults are appended for mac/prebuilt path ───────
console.log('\n=== case 4: boxlite provider env is synthesized ===\n');
{
  const dir = mkdtempSync(join(tmpdir(), 'qdeploy-gate5-'));
  const envPath = join(dir, '.env');

  runGate5(dir, 'v0.24.0', 'boxlite', {
    BOXLITE_ENDPOINT: 'http://127.0.0.1:7331',
    BOXLITE_API_TOKEN: 'box-token',
    BOXLITE_IMAGE: 'cap-boxlite:v0.24.0',
  });

  const env = parseEnv(readFileSync(envPath, 'utf8'));
  assert(env.CAP_SANDBOX_PROVIDER === 'boxlite',
    'case4: CAP_SANDBOX_PROVIDER=boxlite is written');
  assert(env.BOXLITE_ENDPOINT === 'http://127.0.0.1:7331',
    'case4: BOXLITE_ENDPOINT is written from process env');
  assert(env.BOXLITE_API_TOKEN === 'box-token',
    'case4: BOXLITE_API_TOKEN is written from process env');
  assert(env.BOXLITE_IMAGE === 'cap-boxlite:v0.24.0',
    'case4: BOXLITE_IMAGE is written from process env');
  assert(env.BOXLITE_PROVIDER_PRIORITY === '100',
    'case4: BoxLite default priority is appended');
  assert(env.BOXLITE_TERMINAL_MODE === 'pty',
    'case4: BoxLite terminal mode default is appended');
}

// ── summary ──────────────────────────────────────────────────────────────────
console.log(`\n${'─'.repeat(56)}`);
console.log(`Results: ${passed} passed, ${failed} failed`);
if (failed === 0) { console.log('ALL TESTS PASSED'); process.exit(0); }
else { console.error('SOME TESTS FAILED'); process.exit(1); }
