/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulesRouteImport } from './routes/_app/schedules'
import { Route as AppRepositoriesRouteImport } from './routes/_app/repositories'
import { Route as AppImagesRouteImport } from './routes/_app/images'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApiRouteImport } from './routes/_app/api'
import { Route as AppTasksNewRouteImport } from './routes/_app/tasks/new'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'
import { Route as AppHelpSandboxImagesRouteImport } from './routes/_app/help/sandbox-images'
import { Route as AppHelpResendSmtpRouteImport } from './routes/_app/help/resend-smtp'
import { Route as AppHelpForgeTokensRouteImport } from './routes/_app/help/forge-tokens'
import { Route as AppTasksTaskIdTranscriptRouteImport } from './routes/_app/tasks/$taskId_.transcript'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRoute = AppRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksNewRoute = AppTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpSandboxImagesRoute = AppHelpSandboxImagesRouteImport.update({
  id: '/help/sandbox-images',
  path: '/help/sandbox-images',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpResendSmtpRoute = AppHelpResendSmtpRouteImport.update({
  id: '/help/resend-smtp',
  path: '/help/resend-smtp',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpForgeTokensRoute = AppHelpForgeTokensRouteImport.update({
  id: '/help/forge-tokens',
  path: '/help/forge-tokens',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdTranscriptRoute =
  AppTasksTaskIdTranscriptRouteImport.update({
    id: '/tasks/$taskId_/transcript',
    path: '/tasks/$taskId/transcript',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/workspace': typeof WorkspaceRoute
  '/api': typeof AppApiRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/images': typeof AppImagesRoute
  '/repositories': typeof AppRepositoriesRoute
  '/schedules': typeof AppSchedulesRoute
  '/settings': typeof AppSettingsRoute
  '/help/forge-tokens': typeof AppHelpForgeTokensRoute
  '/help/resend-smtp': typeof AppHelpResendSmtpRoute
  '/help/sandbox-images': typeof AppHelpSandboxImagesRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/$taskId/transcript': typeof AppTasksTaskIdTranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/workspace': typeof WorkspaceRoute
  '/api': typeof AppApiRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/images': typeof AppImagesRoute
  '/repositories': typeof AppRepositoriesRoute
  '/schedules': typeof AppSchedulesRoute
  '/settings': typeof AppSettingsRoute
  '/help/forge-tokens': typeof AppHelpForgeTokensRoute
  '/help/resend-smtp': typeof AppHelpResendSmtpRoute
  '/help/sandbox-images': typeof AppHelpSandboxImagesRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/new': typeof AppTasksNewRoute
  '/tasks/$taskId/transcript': typeof AppTasksTaskIdTranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/resume': typeof ResumeRoute
  '/workspace': typeof WorkspaceRoute
  '/_app/api': typeof AppApiRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/images': typeof AppImagesRoute
  '/_app/repositories': typeof AppRepositoriesRoute
  '/_app/schedules': typeof AppSchedulesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/help/forge-tokens': typeof AppHelpForgeTokensRoute
  '/_app/help/resend-smtp': typeof AppHelpResendSmtpRoute
  '/_app/help/sandbox-images': typeof AppHelpSandboxImagesRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/new': typeof AppTasksNewRoute
  '/_app/tasks/$taskId_/transcript': typeof AppTasksTaskIdTranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/login'
    | '/resume'
    | '/workspace'
    | '/api'
    | '/dashboard'
    | '/history'
    | '/images'
    | '/repositories'
    | '/schedules'
    | '/settings'
    | '/help/forge-tokens'
    | '/help/resend-smtp'
    | '/help/sandbox-images'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/$taskId/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/login'
    | '/resume'
    | '/workspace'
    | '/api'
    | '/dashboard'
    | '/history'
    | '/images'
    | '/repositories'
    | '/schedules'
    | '/settings'
    | '/help/forge-tokens'
    | '/help/resend-smtp'
    | '/help/sandbox-images'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tasks/$taskId/transcript'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accounts'
    | '/login'
    | '/resume'
    | '/workspace'
    | '/_app/api'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/images'
    | '/_app/repositories'
    | '/_app/schedules'
    | '/_app/settings'
    | '/_app/help/forge-tokens'
    | '/_app/help/resend-smtp'
    | '/_app/help/sandbox-images'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/new'
    | '/_app/tasks/$taskId_/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  LoginRoute: typeof LoginRoute
  ResumeRoute: typeof ResumeRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedules': {
      id: '/_app/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories': {
      id: '/_app/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images': {
      id: '/_app/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/new': {
      id: '/_app/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/sandbox-images': {
      id: '/_app/help/sandbox-images'
      path: '/help/sandbox-images'
      fullPath: '/help/sandbox-images'
      preLoaderRoute: typeof AppHelpSandboxImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/resend-smtp': {
      id: '/_app/help/resend-smtp'
      path: '/help/resend-smtp'
      fullPath: '/help/resend-smtp'
      preLoaderRoute: typeof AppHelpResendSmtpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/forge-tokens': {
      id: '/_app/help/forge-tokens'
      path: '/help/forge-tokens'
      fullPath: '/help/forge-tokens'
      preLoaderRoute: typeof AppHelpForgeTokensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/transcript': {
      id: '/_app/tasks/$taskId_/transcript'
      path: '/tasks/$taskId/transcript'
      fullPath: '/tasks/$taskId/transcript'
      preLoaderRoute: typeof AppTasksTaskIdTranscriptRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppImagesRoute: typeof AppImagesRoute
  AppRepositoriesRoute: typeof AppRepositoriesRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppHelpForgeTokensRoute: typeof AppHelpForgeTokensRoute
  AppHelpResendSmtpRoute: typeof AppHelpResendSmtpRoute
  AppHelpSandboxImagesRoute: typeof AppHelpSandboxImagesRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksNewRoute: typeof AppTasksNewRoute
  AppTasksTaskIdTranscriptRoute: typeof AppTasksTaskIdTranscriptRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppImagesRoute: AppImagesRoute,
  AppRepositoriesRoute: AppRepositoriesRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppHelpForgeTokensRoute: AppHelpForgeTokensRoute,
  AppHelpResendSmtpRoute: AppHelpResendSmtpRoute,
  AppHelpSandboxImagesRoute: AppHelpSandboxImagesRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksNewRoute: AppTasksNewRoute,
  AppTasksTaskIdTranscriptRoute: AppTasksTaskIdTranscriptRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountsRoute: AccountsRoute,
  LoginRoute: LoginRoute,
  ResumeRoute: ResumeRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
