import type {
  ExactHostGitCredential,
  SandboxCommandExecutionRequest,
  SandboxDeliverWorkspaceArgs,
  SandboxInventoryReconcileInput,
  SandboxPhysicalCleanupResult,
  SandboxProviderPrivateSecretFileWriteRequest,
  SandboxRunCleanupAuthorization,
  SandboxSecretFileWriteRequest,
  SandboxWorkspaceCommandExecutionRequest,
} from '../src/index.js';

declare const credential: ExactHostGitCredential;
declare const cleanupAuthorization: SandboxRunCleanupAuthorization;
declare const physicalCleanup: SandboxPhysicalCleanupResult;

const authorizedReconciliation: SandboxInventoryReconcileInput = {
  protectedTaskIds: [],
  canReap: ({ taskId, providerSandboxId }) =>
    taskId.length > 0 && providerSandboxId.length > 0,
};
void authorizedReconciliation;

// @ts-expect-error destructive inventory reconciliation requires live authorization
const unauthorizedReconciliation: SandboxInventoryReconcileInput = {
  protectedTaskIds: [],
};
void unauthorizedReconciliation;

const ordinaryRequest: SandboxCommandExecutionRequest = {
  command: 'git status',
};
void ordinaryRequest;

const ordinaryAuthHeader = {
  command: 'git status',
  authHeader: 'Authorization: Basic secret',
};
// @ts-expect-error ordinary execution requests cannot structurally carry auth headers
const rejectedOrdinaryAuth: SandboxCommandExecutionRequest = ordinaryAuthHeader;
void rejectedOrdinaryAuth;

const ordinaryCredential = { command: 'git status', credential };
// @ts-expect-error ordinary execution requests cannot structurally carry credentials
const rejectedOrdinaryCredential: SandboxCommandExecutionRequest = ordinaryCredential;
void rejectedOrdinaryCredential;

const ordinarySecret = { command: 'git status', secret: 'secret' };
// @ts-expect-error ordinary execution requests cannot structurally carry secrets
const rejectedOrdinarySecret: SandboxCommandExecutionRequest = ordinarySecret;
void rejectedOrdinarySecret;

const ordinaryEnv = { command: 'git status', env: { TOKEN: 'secret' } };
// @ts-expect-error ordinary execution requests cannot carry an environment map
const rejectedOrdinaryEnv: SandboxCommandExecutionRequest = ordinaryEnv;
void rejectedOrdinaryEnv;

const ordinaryStdin = { command: 'git status', stdin: 'secret' };
// @ts-expect-error ordinary execution requests cannot carry stdin
const rejectedOrdinaryStdin: SandboxCommandExecutionRequest = ordinaryStdin;
void rejectedOrdinaryStdin;

const ordinaryArgv = { command: 'git status', argv: ['secret'] };
// @ts-expect-error ordinary execution requests cannot carry argv
const rejectedOrdinaryArgv: SandboxCommandExecutionRequest = ordinaryArgv;
void rejectedOrdinaryArgv;

const workspaceRequest: SandboxWorkspaceCommandExecutionRequest = {
  command: 'git status',
};
void workspaceRequest;

const workspaceEnv = { command: 'git status', env: { TOKEN: 'secret' } };
// @ts-expect-error workspace commands cannot carry an environment map
const rejectedWorkspaceEnv: SandboxWorkspaceCommandExecutionRequest = workspaceEnv;
void rejectedWorkspaceEnv;

const workspaceStdin = { command: 'git status', stdin: 'secret' };
// @ts-expect-error workspace commands cannot carry stdin
const rejectedWorkspaceStdin: SandboxWorkspaceCommandExecutionRequest = workspaceStdin;
void rejectedWorkspaceStdin;

const credentialedDelivery: SandboxDeliverWorkspaceArgs = {
  credential,
  branch: 'master',
  commitMessage: 'Apply task changes',
  afterSandboxCleanup: async (authorization) => {
    void authorization;
  },
  settleSandboxCleanupAttempt: async (authorization, physical) => {
    void authorization;
    void physical;
  },
};
void credentialedDelivery;
void credentialedDelivery.afterSandboxCleanup?.(cleanupAuthorization);
void credentialedDelivery.settleSandboxCleanupAttempt?.(
  cleanupAuthorization,
  physicalCleanup,
);

// @ts-expect-error canonical delivery cannot also carry a raw authHeader
const mixedDelivery: SandboxDeliverWorkspaceArgs = {
  credential,
  authHeader: 'Authorization: Basic secret',
  branch: 'master',
  commitMessage: 'Apply task changes',
};
void mixedDelivery;

const legacyDelivery: SandboxDeliverWorkspaceArgs = {
  authHeader: 'Authorization: Basic legacy',
  branch: 'master',
  commitMessage: 'Apply task changes',
};
void legacyDelivery;

const secretWrite: SandboxSecretFileWriteRequest = {
  kind: 'git-http-credential',
  credential,
};
void secretWrite;

const callerSelectedSecretPath: SandboxSecretFileWriteRequest = {
  kind: 'git-http-credential',
  credential,
  // @ts-expect-error secret-file location is generated by the provider port
  path: '/tmp/caller-selected',
};
void callerSelectedSecretPath;

const providerPrivateWrite: SandboxProviderPrivateSecretFileWriteRequest = {
  path: '/run/cap/credential',
  content: new Uint8Array(),
  mode: 0o600,
};
void providerPrivateWrite;

const providerPrivateCommand: SandboxProviderPrivateSecretFileWriteRequest = {
  path: '/run/cap/credential',
  content: new Uint8Array(),
  mode: 0o600,
  // @ts-expect-error even provider-private file input cannot become a command
  command: 'printf secret',
};
void providerPrivateCommand;

// @ts-expect-error RedactedSecret deliberately exposes no reveal method
credential.authorizationHeader.reveal();
