/**
 * Wire-compatibility fixture for the two request surfaces this change tightens.
 *
 * `surface-impact.json` declares `runtimeWireBehavior: "changed"`, and the
 * repository's metadata gate demands a fixture for that — correctly. This is it.
 *
 * Per tightened field it pins BOTH edges:
 *
 *   - the input that WAS accepted and is now rejected, so a later relaxation
 *     fails here rather than silently restoring the drift;
 *   - the input that must keep working, so a further tightening fails here
 *     rather than silently breaking a caller.
 *
 * A one-sided fixture would only pin the direction the change happened to move,
 * which is the half that needs no protection.
 *
 * WHAT THESE ARE NOT: exploitable defects. Every account route is admin-gated,
 * and the OTP code is generated by the api itself, so a real code always matched
 * the six-digit rule. These are drifts between a rule the contract declared and
 * the one the api enforced — which is the whole subject of this change, and
 * overclaiming it as a vulnerability is the failure mode this programme keeps
 * catching in itself.
 *
 * Measured against the pre-change tree: all three over-long inputs below were
 * ACCEPTED there. That is what makes them evidence rather than restatement.
 */

import assert from 'node:assert/strict';
import test from 'node:test';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

// Straight from the contract, because that is what the controllers hand to
// `ZodValidationPipe` now. They were briefly aliased inside
// `accounts.service.ts`, which broke the execution gate's attribution and was the
// private rename this package's spec forbids; the aliases are gone.
const {
  AdminCreateAccountRequestSchema,
  AdminResetPasswordRequestSchema,
  AdminSetEnabledRequestSchema,
  AdminSetRoleRequestSchema,
  OtpRequestRequestSchema,
  OtpVerifyRequestSchema,
} = require('@cap-console/contracts');

/** The contract's stated ceiling: `PasswordSchema = z.string().min(8).max(200)`. */
const AT_LIMIT = 'a'.repeat(200);
const OVER_LIMIT = 'a'.repeat(201);

const createBody = (overrides) => ({
  email: 'admin@example.com',
  name: 'Example Admin',
  role: 'admin',
  initialCredential: 'password',
  password: 'a-good-password',
  ...overrides,
});

// ---- passwords: the argon2 ceiling the local copy dropped -------------------

test('create rejects a password past the contract ceiling, and accepts it at the ceiling', () => {
  // The bound exists "so a single field cannot be used to exhaust the argon2
  // hasher" — the contract's own words. The local DTO was `.min(8)` with no
  // upper bound, so this input was accepted before this change.
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(createBody({ password: OVER_LIMIT })).success,
    false,
  );
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(createBody({ password: AT_LIMIT })).success,
    true,
    'the ceiling is 200, not 199 — a further tightening must fail here',
  );
});

test('reset-password enforces the same ceiling on both edges', () => {
  assert.equal(AdminResetPasswordRequestSchema.safeParse({ password: OVER_LIMIT }).success, false);
  assert.equal(AdminResetPasswordRequestSchema.safeParse({ password: AT_LIMIT }).success, true);
});

test('the minimum length is unchanged by this change', () => {
  // Converging must not move the floor while restoring the ceiling.
  assert.equal(AdminResetPasswordRequestSchema.safeParse({ password: 'a'.repeat(7) }).success, false);
  assert.equal(AdminResetPasswordRequestSchema.safeParse({ password: 'a'.repeat(8) }).success, true);
});

test('the display name gains the same ceiling', () => {
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(
      createBody({ name: OVER_LIMIT, initialCredential: 'otp-only', password: undefined }),
    ).success,
    false,
  );
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(
      createBody({ name: AT_LIMIT, initialCredential: 'otp-only', password: undefined }),
    ).success,
    true,
  );
});

// ---- shapes that must NOT have moved ---------------------------------------

test('the cross-field password rule survives the convergence', () => {
  // `initialCredential: "password"` requires a password; `otp-only` forbids
  // needing one. This lived in the local copy as a `.refine` and lives in the
  // contract as the same refinement — a convergence that dropped it would turn a
  // 400 into an account created with no credential.
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(createBody({ password: undefined })).success,
    false,
    'a password-credential account with no password must still be a 400',
  );
  assert.equal(
    AdminCreateAccountRequestSchema.safeParse(
      createBody({ initialCredential: 'otp-only', password: undefined }),
    ).success,
    true,
  );
});

test('role and enabled bodies are unchanged', () => {
  assert.equal(AdminSetRoleRequestSchema.safeParse({ role: 'admin' }).success, true);
  assert.equal(AdminSetRoleRequestSchema.safeParse({ role: 'member' }).success, true);
  assert.equal(AdminSetRoleRequestSchema.safeParse({ role: 'root' }).success, false);
  assert.equal(AdminSetEnabledRequestSchema.safeParse({ allowed: true }).success, true);
  assert.equal(AdminSetEnabledRequestSchema.safeParse({ allowed: 'yes' }).success, false);
});

// ---- OTP: six digits, and a normalised address -----------------------------

test('the OTP code must be six digits, and six digits still works', () => {
  const email = 'operator@example.com';
  assert.equal(OtpVerifyRequestSchema.safeParse({ email, code: '12345' }).success, false);
  assert.equal(OtpVerifyRequestSchema.safeParse({ email, code: '1234567' }).success, false);
  assert.equal(OtpVerifyRequestSchema.safeParse({ email, code: '12a456' }).success, false);
  assert.equal(OtpVerifyRequestSchema.safeParse({ email, code: '123456' }).success, true);
});

test('a malformed address is rejected and a padded one is normalised', () => {
  assert.equal(OtpRequestRequestSchema.safeParse({ email: 'not-an-email' }).success, false);
  const padded = OtpRequestRequestSchema.safeParse({ email: '  operator@example.com  ' });
  assert.equal(padded.success, true);
  assert.equal(
    padded.data.email,
    'operator@example.com',
    'the contract trims — a stray space used to fail the account lookup silently',
  );
});

test('rejecting a malformed address does not leak account existence', () => {
  // The surface answers identically for a known and an unknown address on
  // purpose ("Request for an unknown email reveals nothing"). A 400 for input
  // that could not name ANY account does not distinguish the two, which is the
  // property that had to survive this tightening.
  const known = OtpRequestRequestSchema.safeParse({ email: 'operator@example.com' });
  const unknown = OtpRequestRequestSchema.safeParse({ email: 'nobody@example.com' });
  assert.equal(known.success, unknown.success);
});
